[repository]
name = "hyprland-vines"
authors = ["s4id"]

[hyprland-vines]
description = "A Hyprland plugin that adds decorative vines with time-based growth around windows. Vines start small at midnight, grow throughout the day, and turn orange after 5 PM."
authors = ["s4id"]
output = "borders-plus-plus.so"
build = [
    "make all",
]
